### ISSUE TITLE
[Warning] of online processor count 

### ISSUE THREAD

**Issue by dhxsy1994** [alibaba/dragonwell8#37] opened 2019-07-10 03:07 UTC
**Description**
The testing device is kunlun-9032 with 1024 processors, when I run java program it will report the warning:
OpenJDK 64-Bit Server VM warning: sched_getaffinity failed (Invalid argument)- using online processor count (1024) which may exceed available processors

**Expected behavior**
the warning may also can reproduce on other jdk versions, but it may not fixed on redhat version, it should be fixed.
seen: https://bugs.openjdk.java.net/browse/JDK-8157478  

**JDK version**
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (Alibaba Dragonwell 8.0.0-b48) (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell 8.0.0-b48) (build 25.212-b04, mixed mode)

**Execution environment**
 - OS and version: redhat 7.2
 - Number of CPU cores: 1024
 - Inside Linux container? No

**Comment by luchsh** [comment] 2019-07-16 09:30
Hi dhxsy1994,  thanks for reporting!
Unfortunately, I cannot find a powerful machine like yours to reproduce this case.
the warning was produced by [this code](https://github.com/alibaba/dragonwell8_hotspot/blob/master/src/os/linux/vm/os_linux.cpp#L5303).
As I read from the code and Linux manual (man 3 CPU_SET), the maximum number of processors currently supported by CPU affinity is `1024` (CPU_SETSIZE). Are you suggesting that something is wrong with handling the 1024th core?

**Comment by dhxsy1994** [comment] 2019-07-21 16:25
The range of cpu number is 0~1023, sched_getaffinity() may not work with the 1024th cpu, this processor is not online. Maybe this warning is not important, many versions have this warning with my test. Thanks!

**Comment by luchsh** [comment] 2019-07-23 01:37
> The range of cpu number is 0~1023, sched_getaffinity() may not work with the 1024th cpu, this processor is not online. Maybe this warning is not important, many versions have this warning with my test. Thanks!

Indeed, Dragonwell does not ship any processors related patches in the GA release, it's behavior ought to exactly the same as the reference implementation. I was just trying to figure out whether sched_getaffinity() and JDK's behavior was correct about the 1024th (id=1024) cpu.
If it looks like incorrect behavior, maybe we should raise a bug to upstream OpenJDK.

**Comment by luchsh** [comment] 2019-08-02 04:00
I'm closing this issue, since it sounds like a problem upstream OpenJDK also has, please re-open if you feel that we should do something in Dragonwell.
Thanks

**Closed by luchsh** 2019-08-02 04:00 UTC

**Comment by ErichLoew** [comment] 2022-12-24 10:22
The topic is back:
My CPU: Intel(R) Core(TM)2 Duo CPU E8400
Kernel: 6.1.1
OS: OpenSUSE Leap 15.2
java: java 19 2022-09-20
          Java (TM) SE Runtime Environment (build 19+36-2238)
          Java HotSpot(TM) 64-Bit Server VM (build 19+36-2238, mixed 
          mode, sharing)

Since kernel 6.1.0 I see: Java HotSpot(TM) 64-Bit Server VM warning: sched_getaffinity failed (Invalid argument)- using online processor count (2) which may exceed available processors

On kernel 6.0.12 and older: issue not observable

I jumped directly from 6.0.12 to 6.1.0 and then to 6.1.1

My interpretation: something in recent kernel interfaces to USER world irritates JAVA.
