### ISSUE TITLE
vertx-sql-client core dump with wisp2

### ISSUE THREAD

**Issue by yueliangwen** [alibaba/dragonwell8#216] opened 2021-03-22 10:43 UTC
**Description**
vertx-sql-client based on netty.

**Steps to Reproduce**
1. Download the dump.tar.gz
2. Read the README.adoc
3. Configure the PostgreSQL instance
4. See core dump

[dump.tar.gz](https://github.com/alibaba/dragonwell8/files/6181421/dump.tar.gz)
[hs_err_pid4247.log](https://github.com/alibaba/dragonwell8/files/6181439/hs_err_pid4247.log)
[replay_pid4247.log](https://github.com/alibaba/dragonwell8/files/6181440/replay_pid4247.log)

You may modify some configuration code to connect the PostgreSQL instance.
![image](https://user-images.githubusercontent.com/1107708/111977686-fd11cc00-8b3d-11eb-9333-27ed4609f7c1.png)

The README.adoc image
![image](https://user-images.githubusercontent.com/1107708/111978028-6b568e80-8b3e-11eb-9b1b-57e286ec974f.png)

**Expected behavior**
The case should not be core dump.

**JDK version**
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (Alibaba Dragonwell 8.6.5) (build 1.8.0_282-b1)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell 8.6.5) (build 25.282-b1, mixed mode)

**Execution environment**
 - OS and version: Linux ubuntu 5.8.0-45-generic #51~20.04.1-Ubuntu SMP Tue Feb 23 13:46:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by zhengxiaolinX** [comment] 2021-03-23 12:55
Thanks for opening this issue. You can simply add one JVM option `-XX:CompileCommand=exclude,io.vertx.sqlclient.impl.SocketConnectionBase::lambda\$init\$0` by excluding this method from compilation or `-XX:-TieredCompilation` by disable the C1 compiler to work around with this issue in your case if needed. This problem happens because some dead locals in debug info of `MonitorExit` node in synchronized methods, compiled by the C1 compiler, don't get cleaned, and it is a somewhat rare case. I will file a patch afterward to fix this problem.

**Comment by yueliangwen** [comment] 2021-03-24 05:30
@zhengxiaolinX Thanks for your suggestion.

**Comment by zhengxiaolinX** [comment] 2021-03-31 10:50
Could you please have a try for the latest build, in which the fix for Wisp exists, when you are available? I hope everything goes well this time.
Release page: [Dragonwell8.6.6](https://github.com/alibaba/dragonwell8/releases)
Thanks in advance.

**Comment by yueliangwen** [comment] 2021-04-01 04:09
@zhengxiaolinX Thanks, it worked as expected.

**Comment by zhengxiaolinX** [comment] 2021-04-01 04:25
Thanks again for providing us with this great test for reproducing this issue, which helps us solve it without any difficulty. I'll close this issue and please feel free to reopen it if needed.

**Closed by zhengxiaolinX** 2021-04-01 04:25 UTC
Labels: bug
