### ISSUE TITLE
compile error on build with "cannot find symbol TenantContainer"

### ISSUE THREAD

**Issue by dinglevin** [alibaba/dragonwell8#96] opened 2020-04-09 03:12 UTC
Here is my step:
1. use docker ubuntu:18.04
2. run get_source_dragonwell.sh to fetch sources.
3. install necessary dependencies, ./configure pass
4. install boot jdk:
> Tools summary:
> * Boot JDK:       openjdk version "1.8.0_232" OpenJDK Runtime Environment (Alibaba Dragonwell 8.2.2-b82) (build 1.8.0_232-b09) OpenJDK 64-Bit Server VM (Alibaba Dragonwell 8.2.2-b82) (build 25.232-b09, mixed mode)  (at /root/j2sdk-image)
> * Toolchain:      gcc (GNU Compiler Collection)
> * C Compiler:     Version 7.5.0 (at /usr/bin/gcc)
> * C++ Compiler:   Version 7.5.0 (at /usr/bin/g++)
5. run `./make.sh release`, then I got following errors:
>Starting langtools
make[1]: Entering directory '/dragonwell8/langtools/make'
SetupJavaCompiler(BOOT_JAVAC) 
 [2] JAVAC := /root/j2sdk-image/bin/javac 
 [3] SERVER_DIR := 
 [4] SERVER_JVM := /root/j2sdk-image/bin/java -verbosegc -d64 -Xms1G -Xmx2500M 
 [5] FLAGS := -XDignore.symbol.file=true -g -Xlint:all,-deprecation -Werror                     
SetupJavaCompilation(BUILD_TOOLS) 
 [2] SETUP := BOOT_JAVAC 
 [3] DISABLE_SJAVAC := true 
 [4] ADD_JAVAC_FLAGS := -Xprefer:source 
 [5] SRC := /dragonwell8/langtools/make/tools /dragonwell8/langtools/src/share/classes 
 [6] INCLUDES := compileproperties genstubs 
 [7] BIN := /dragonwell8/build/linux-x86_64-normal-server-release/langtools/btclasses                   
/bin/mkdir -p /dragonwell8/build/linux-x86_64-normal-server-release/langtools/btclasses
/bin/rm -f /dragonwell8/build/linux-x86_64-normal-server-release/langtools/btclasses/_the.BUILD_TOOLS_batch /dragonwell8/build/linux-x86_64-normal-server-release/langtools/btclasses/_the.BUILD_TOOLS_batch.tmp
/bin/echo  Writing 2 paths to ' >> /dragonwell8/build/linux-x86_64-normal-server-release/langtools/btclasses/_the.BUILD_TOOLS_batch.tmp'
Writing 2 paths to  >> /dragonwell8/build/linux-x86_64-normal-server-release/langtools/btclasses/_the.BUILD_TOOLS_batch.tmp
/bin/echo Compiling `/usr/bin/wc /dragonwell8/build/linux-x86_64-normal-server-release/langtools/btclasses/_the.BUILD_TOOLS_batch.tmp | /usr/bin/tr -s ' ' | /usr/bin/cut -f 2 -d ' '` files for BUILD_TOOLS
Compiling 2 files for BUILD_TOOLS
( /root/j2sdk-image/bin/javac -XDignore.symbol.file=true -g -Xlint:all,-deprecation -Werror  -Xprefer:source -implicit:none -sourcepath "/dragonwell8/langtools/make/tools:/dragonwell8/langtools/src/share/classes" -d /dragonwell8/build/linux-x86_64-normal-server-release/langtools/btclasses  @/dragonwell8/build/linux-x86_64-normal-server-release/langtools/btclasses/_the.BUILD_TOOLS_batch.tmp && /bin/mv /dragonwell8/build/linux-x86_64-normal-server-release/langtools/btclasses/_the.BUILD_TOOLS_batch.tmp /dragonwell8/build/linux-x86_64-normal-server-release/langtools/btclasses/_the.BUILD_TOOLS_batch)
/dragonwell8/langtools/src/share/classes/com/sun/tools/javac/file/ZipFileIndexCache.java:28: error: package com.alibaba.tenant does not exist
import com.alibaba.tenant.TenantContainer;
                         ^
/dragonwell8/langtools/src/share/classes/com/sun/tools/javac/file/ZipFileIndexCache.java:29: error: package com.alibaba.tenant does not exist
import com.alibaba.tenant.TenantGlobals;
                         ^
/dragonwell8/langtools/src/share/classes/com/sun/tools/javac/file/ZipFileIndexCache.java:53: error: cannot find symbol
        if (TenantGlobals.isDataIsolationEnabled() && TenantContainer.current() != null) {
            ^
  symbol:   variable TenantGlobals
  location: class ZipFileIndexCache
/dragonwell8/langtools/src/share/classes/com/sun/tools/javac/file/ZipFileIndexCache.java:53: error: cannot find symbol
        if (TenantGlobals.isDataIsolationEnabled() && TenantContainer.current() != null) {
                                                      ^
  symbol:   variable TenantContainer
  location: class ZipFileIndexCache
/dragonwell8/langtools/src/share/classes/com/sun/tools/javac/file/ZipFileIndexCache.java:54: error: cannot find symbol
            return TenantContainer.current()
                   ^
  symbol:   variable TenantContainer
  location: class ZipFileIndexCache
5 errors
make[1]: Leaving directory '/dragonwell8/langtools/make'
make[1]: *** No rule to make target 'all', needed by 'default'.  Stop.
/dragonwell8//make/Main.gmk:84: recipe for target 'langtools-only' failed
make: *** [langtools-only] Error 2
Failed: /dragonwell8/build/linux-x86_64-normal-server-release/images/j2sdk-image/bin/java -version

Any step I miss here?

**Comment by luchsh** [comment] 2020-04-09 03:46
It was caused by this patch,
https://github.com/alibaba/dragonwell8_langtools/commit/d09c9011a749833144a112172516274b50e4be5e

After merging that patch, it requires Dragonwell 8.3.3+ (which will be released very soon) as bootstrap JDK (configure --with-bootjdk=<>) to compile Dragonwell.
Alternatively you may use a prebuilt docker image `dragonwelljdk/build_jdk :8u` to compile, the image contains a release candidate JDK build of Dragonwell 8.3.3.

**Closed** 2020-04-10 11:23 UTC
