### ISSUE TITLE
能发一篇如何调试 hotsopt 的文章吗?

### ISSUE THREAD

**Issue by sc-ik** [alibaba/dragonwell8#67] opened 2019-12-25 14:16 UTC
我搜索了很多文章, 但是我很头疼 因为 哪些文章大多都是复制 的

解决不了我的问题,

我现在使用的是的 

Alibaba_Dragonwell_8.1.1-GA_Linux_x64.tar.gz
Alibaba_Dragonwell_8.1.1-GA_source.tar.gz

**Comment by sc-ik** [comment] 2019-12-25 15:30
我是使用 LLDB 9.0  抛出 SIGSEGV (signal SIGSEGV: invalid address (fault address: 0x0)) 问题.

但是 我也设置了 process handle SIGSEGV --stop=false 还是不行

**Comment by luchsh** [comment] 2019-12-26 05:32
Hi, to debug Dragonwell is almost the same as debugging any other programs.
SIGSEGV is employed to trigger safepoint on mutator threads, so you may want to completely disable it, the GDB command is `handle SIGSEGV noprint nostop pass`.

**Comment by luchsh** [comment] 2019-12-26 05:36
btw, please use the Dragonwell issue template, for informal discussions, please go to the Dragonwell User support Dingtalk group.
[QR code](https://github.com/alibaba/dragonwell8/wiki/images/dingtalk_group_QR.png)

**Comment by luchsh** [comment] 2019-12-28 03:25
closing this PR, not a bug and reporter did not follow our convention.

**Closed by luchsh** 2019-12-28 03:25 UTC
