### ISSUE TITLE
[Bug] Dragonwell8.2.2: ClassLoader.getResources() can not work properly

### ISSUE THREAD

**Issue by Instein98** [alibaba/dragonwell8#99] opened 2020-04-29 03:07 UTC
**Description**
When executing the code `ClassLoader.getResources("META-INF/MANIFEST.MF")`, J9(1.8.0_232) can find several resources: 
```
jar:file:/home/JVMs/j9-8u232-b09/jre/lib/rt.jar!/META-INF/MANIFEST.MF
jar:file:/home/JVMs/j9-8u232-b09/jre/lib/resources.jar!/META-INF/MANIFEST.MF
jar:file:/home/JVMs/j9-8u232-b09/jre/lib/jsse.jar!/META-INF/MANIFEST.MF
jar:file:/home/JVMs/j9-8u232-b09/jre/lib/charsets.jar!/META-INF/MANIFEST.MF
jar:file:/home/JVMs/j9-8u232-b09/jre/lib/jce.jar!/META-INF/MANIFEST.MF
```
But Dragonwell(8.2.2) finds nothing. However, those jar files with the same name exist in the corresponding directory of Dragonwell(8.2.2). These resources exist, but Dragonwell did not find it.

**Steps to Reproduce**
[test2.zip](https://github.com/alibaba/dragonwell8/files/4549627/test2.zip)
1. Extract it
2. Compile test2.java
3. Run the command `java test2`

**Expected behavior**
It is expected to print:
```
jar:file:/home/JVMs/dragonwell8.2.2/jre/lib/rt.jar!/META-INF/MANIFEST.MF
jar:file:/home/JVMs/dragonwell8.2.2/jre/lib/resources.jar!/META-INF/MANIFEST.MF
jar:file:/home/JVMs/dragonwell8.2.2/jre/lib/jsse.jar!/META-INF/MANIFEST.MF
jar:file:/home/JVMs/dragonwell8.2.2/jre/lib/charsets.jar!/META-INF/MANIFEST.MF
jar:file:/home/JVMs/dragonwell8.2.2/jre/lib/jce.jar!/META-INF/MANIFEST.MF
```
But actually it print nothing.

**JDK version**
```
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (Alibaba Dragonwell 8.2.2-b82) (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell 8.2.2-b82) (build 25.232-b09, mixed mode)
```

**Execution environment**
 - OS and version: Ubuntu 16.04.6 LTS
 - CPU model: Intel(R) Xeon(R) CPU E5-4610 v4 @ 1.80GHz
 - Number of CPU cores: 4CPUs, each has 10 cores
 - Size of physical memory: 16384 MB * 20
 - Inside Linux container? No

**Comment by luchsh** [comment] 2020-04-29 03:20
Thanks for reporting! will take a look

**Comment by zhengxiaolinX** [comment] 2020-04-30 02:49
Thanks for reporting. I can reproduce this behavior. I also tested latest versions of OpenJDK8, OpenJDK11 and OpenJDK15 and there's no output either. It seems J9 has some differences and I will look into it.

**Comment by zhengxiaolinX** [comment] 2020-05-03 07:38
I debugged into it and TL;DR, I consider that it's not a bug.
For bootstrap classloader's resources, JDK will firstly read from a file names `meta-index` under `jre/lib`. When generating this file, the `META-INF/MANIFEST.MF` file is filtered out by `BuildMetaIndex.java` inside the `build.tools.buildmetaindex` package under the `jdk/make/src/classes` directory. See the comments:
```
* Notice the fact that every jar file contains at least the manifest file, so when
* we say "jar file containing only class file", we don't include that file.
```
Also same as the code below,
```
/* We only look at the non-directory entry.
    MANIFEST file is also skipped. */
if (entry.isDirectory()
  || name.equals("META-INF/MANIFEST.MF")) {
    continue;
}
```
This file is skipped in OpenJDK. So not a problem and I'll close this issue first.
Please feel free to reopen this issue.

**Closed by zhengxiaolinX** 2020-05-03 07:38 UTC
